workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - PractCoach
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - xcodebuild -project ios/App/App.xcodeproj -scheme App -configuration Release -sdk iphoneos -derivedDataPath build DEVELOPMENT_TEAM=7M3455ZY22 CODE_SIGN_STYLE=Automatic